apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-exporter
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    app: frontend
