services:
  mysqld-exporter:
    image: prom/mysqld-exporter:v0.14.0
    container_name: mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "${MYSQL_EXP_USER}:${MYSQL_EXP_PASSWORD}@tcp(mysql:3307)/"
    networks:
      - monitoring-net
    ports:
      - "${MYSQL_EXPORTER_PORT}:9104"
    depends_on:
      - mysql
