apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: {{ .Values.mysql.namespace | default "database" }}
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--config.my-cnf=" 
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              value: "{{ .Values.datasource.user }}:{{ .Values.datasource.password }}@tcp({{ .Values.datasource.host }}:3306)/"
