apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: {{ .Values.mysql.namespace | default "database" }}
  labels:
    app: mysql-exporter
spec:
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
  selector:
    app: mysql-exporter
