grafana:
  adminPassword: admin
  persistence:
    enabled: true
    storageClassName: local-path
    accessModes: ["ReadWriteOnce"]
    size: 2Gi
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: { } 
    serviceMonitorSelector: { }
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
