replicaCount: 2

image:
  repository: nginxdemos/hello
  tag: latest

service:
  type: ClusterIP
  port: 5099

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

metrics:
  enabled: true
  path: /metrics
  portName: http

prometheus:
  namespace: monitoring

frontend:
  namespace: frontend