replicaCount: 2

image:
  repository: nikitapdev/showcaseapp
  tag: latest

service:
  port: 5000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

metrics:
  enabled: true
  path: /metrics
  portName: http

prometheus:
  namespace: monitoring

frontend:
  namespace: frontend