services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    volumes:
      - ./provisioning/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml:ro
#      - ./provisioning/dashboard-providers.yaml:/etc/grafana/provisioning/dashboards/dashboard-providers.yaml:ro
#      - ./dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-net
volumes:
  grafana-data:
