global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]
        
  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'frontend:8080' ]
      - targets:
          - 'sampletest-frontend-1:8080'
          - 'sampletest-frontend-2:8080'
          - 'sampletest-frontend-3:8080'
          